version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # RabbitMQ main port
      - 15672:15672  # RabbitMQ Management Dashboard port
    volumes:
      - rabbitmq_webinar_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  rabbitmq_webinar_data:
    external: true
